### ISSUE TITLE
Support for Cypress 10x

### ISSUE THREAD

**Issue by paulomanrique** [cmorten/cypress-web-vitals#14]
# Issue

Setup:

- node version: v16.8.0
- cypress-web-vitals version: latest

## Details

Can't install cypress-web-vitals because it's only compatible with Cypress version 9.

Is there any eta for supporting version 10?

**Comment by cmorten** [comment]
No eta as such, just a small project I maintain but sounds good to do! Can perhaps have a look next couple of days, though PRs also very welcome!

We’re there any particular issues / errors you’ve spotted when trying with Cypress 10?

**Comment by mathieun5** [comment]
@cmorten 
I've been using cypress-web-vitals a while now with Cypress v10, no issues so far!

**Comment by cmorten** [comment]
Apologies took a while for me to find some time to take a look 😅 

Looks like it would have probably worked, but package managers were potentially unhappy with the `peerDependency` entry and would have warned / errored depending on setup.

CI updated to test 9.x and 10.x and all looking green - you can check out the `examples` for how to support either major version.
