### ISSUE TITLE
INP Support

### ISSUE THREAD

**Issue by cmorten** [cmorten/cypress-web-vitals#16]
# Issue

## Details

Placeholder to consider support for the new Interaction to New Paint (INP) web vital. See https://web.dev/inp/.

At the time of writing there are a couple of open bugs on the web-vitals package repo, so may be premature to add as "stable" atm. See:

- https://github.com/GoogleChrome/web-vitals/issues/229
- https://github.com/GoogleChrome/web-vitals/issues/230

Open question on whether to / how best to support as this is moving away from a "page load" metric to something more journey based. Wonder whether worth exploring decoupling "record" and "stop" so users can inject their own Cypress driven journey in the middle (pertinent clicks, hovers, etc.), though this would result in losing the current "batteries included" approach of one command "doing it all".

Some notes on implementation detail: https://web.dev/inp/#measure-inp-in-javascript

**Comment by MichaelDimmitt** [comment]
Interesting, makes me wonder if chrome dev tools does a recording when this render checkbox is clicked.

<img width="1510" alt="Screen Shot 2022-09-19 at 12 19 17 PM" src="https://user-images.githubusercontent.com/11463275/191065196-b283d4ff-9598-4b33-a338-3ba6ac034566.png">

**Comment by MichaelDimmitt** [comment]
Being able to record the click through journey will definitely be value-able.

Often analytics such as adobe analytics will show an issue and the only way to recreate is through a series of clicks to trigger that bad state.
