### ISSUE TITLE
Cypress web vitals will not work if credentials or special headers needed to visit the site.

### ISSUE THREAD

**Issue by MichaelDimmitt** [cmorten/cypress-web-vitals#17]
# Issue
Cypress web vitals will not work if credentials or special headers needed to visit the site.
```javascript
cy.visit({
      url: 'https://www.someQaEnvironment.com/',
      headers: {
        "Accept-Encoding": "gzip, deflate"
      },
      auth: {
        username: 'qa',
        password: 'examplepass',  
      }
 });
```

If these are not provided, `ESocket Timeout error`
Took a stab at a fix that worked for me locally so pr coming soon! 🎉
currently in a draft pr: #18 

Setup:

- node version: v16.14.2
- cypress-web-vitals version: 2.0.0
 "cypress-real-events": "^1.7.1",

## Details
1) visitWithWebVitalsSnippet, runs cy.visit after intercept but loses auth and header context.
2) cy.intercept is not grabbing auth param.
3) cy.intercept gives different headers than are required by cy.visit
```javascript
// cy.visit needs:
      headers: {
        "Accept-Encoding": "gzip, deflate"
      },
```

```javascript
// cy.intercept gets:
      headers: {
        accept: "text/html,*/*"
        authorization: "Basic cWF1c2VyOlRlc3RlZDRxdWFsaXR5IQ=="
        connection: "keep-alive"
        cookie:  "some cookie"
        host: "www.example.com"
        user-agent: "some agent"
      }
```
^ because of ( 3) ) , cy.vitals is easy to fix 
but cy.visit is not an easy fix so my draft pr #18  only fixes cy.vitals

**Comment by MichaelDimmitt** [comment]
happy to answer any questions, thanks!

**Comment by cmorten** [comment]
Most cool, look forward to reviewing!
