### ISSUE TITLE
Strict Mode

### ISSUE THREAD

**Issue by kerasai** [cmorten/cypress-web-vitals#22]
# Issue

It'd be useful to have the `cy.vitals()` cause the spec to fail when a check for a threshold is skipped.

## Details

I've noticed a few scenarios where the threshold checks are skipped:

* Tests running in Electron browser
* Browser navigates away from the page via the first input clicks

These specs report that they're passing even though the checks are skipped, and without closer inspection it's not discernible that the check didn't pass.

Perhaps a "strict" option that could be passed into the `cy.vitals()` command to fail when any of the checks are skipped?

**Comment by cmorten** [comment]
Please see the new `strict` option in the latest version
