### ISSUE TITLE
Inp property in WebVitalsThresholds is not optional

### ISSUE THREAD

**Issue by Undestor** [cmorten/cypress-web-vitals#27]
# Issue
Inp property in WebVitalsThresholds is not optional

Setup:
- cypress-web-vitals version: 4.0.0

## Details

In the version 4.0.0 the new threshold property "inp" was introduced. The property is the only **non-optional** property in WebVitalsThresholds. This seems like a mistake or why do i have to define this property if i only want to test e.g. "cls" like
`cy.vitals({ thresholds: { cls: 0.2 } })`

**Comment by cmorten** [comment]
Thanks @Undestor, this is a bug.

**Comment by cmorten** [comment]
@Undestor please can you provide more details (and maybe a reproducing example)?

I've tried:

```js
  it("should meet the custom provided Web Vitals thresholds for a subset of vitals", () => {
    cy.vitals({
      url: "https://www.google.com/",
      thresholds: {
        lcp: 2500,
      },
    });
  });
```

And can see it reporting soley on the LCP metric. The issue appears to be incorrect types 🤦
