### ISSUE TITLE
Cypress 13 support

### ISSUE THREAD

**Issue by schorfES** [cmorten/cypress-web-vitals#29]
# Issue

Setup:

- node version: `18.17.1`
- cypress-web-vitals version: `4.0.1`

## Details

Missing compatibility for cypress `^13` in `peerDependencies`.

**Comment by cmorten** [comment]
Oh wow missed that 13 was out!

Would need to read the changelog to understand if any breaking changes needed https://docs.cypress.io/guides/references/changelog#13-0-0

PRs welcome, it may be as simple as adding to the allowed peer deps, be good to get tests for it to confirm.

**Comment by schorfES** [comment]
I think so, at least the migration guide offers no ground breaking changes that seem to effect this library.
