### ISSUE TITLE
ReportWebVitalsConfig param is not optional in commands.d.ts for reportVitals command

### ISSUE THREAD

**Issue by angry-beaver** [cmorten/cypress-web-vitals#31]
# Issue
`ReportWebVitalsConfig` param is not optional in `commands.d.ts` for `reportVitals` command.

Setup:
- cypress-web-vitals version: 4.1.0

## Details

![Screenshot 2023-12-12 at 14 08 32](https://github.com/cmorten/cypress-web-vitals/assets/9418300/c8d980a0-4644-4ce5-999d-9a65aa8c9ee2)

**Comment by cmorten** [comment]
You’re right, this should be optional.

https://github.com/cmorten/cypress-web-vitals/blob/4eaa29cb1fc498e6c2f886536270004c72523cd2/commands.d.ts#L162 needs updating
